### ISSUE TITLE
Package export map & self-referencing not possible

### ISSUE THREAD

**Issue by Knorgias** [import-js/eslint-plugin-import#2580] opened 2022-10-27 14:36 UTC
## 1. Description

Hey there 👋

I want to be able to self-reference my package without lint errors while using packages `eslint` & `eslint-plugin-import`.

I have a repo tree:

```bash
.
├── foo-bar.js
├── index.js
├── node_modules
├── package-lock.json
├── package.json
└── resolver.cjs
```

with file contents…

`index.js` :

```js
export const foo = 1;
```

`foo-bar.js` :

```js
import { foo } from 'demo-export-map';

console.log(foo);
```

`package.json` :

```json
{
  "name": "demo-export-map",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "type": "module",
  "exports": {
    ".": "./index.js"
  },
  "scripts": {
    "lint": "eslint ."
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "eslint": "^8.26.0",
    "eslint-plugin-import": "^2.26.0"
  }
}
```

## 2. Expected behaviour

`npm run lint` runs without errors

## 3. Actual behaviour

`npm run lint` throws error: 
`error Unable to resolve path to module 'demo-export-map' import/no-unresolved`

You can reproduce it via:

```bash
git clone https://github.com/Knorgias/demo-export-map.git
npm i
npm run lint
```

> Note: I also spotted [this related issue](https://github.com/browserify/resolve/issues/289), and so it seems that the browserify’s resolver doesn't support “exports” mapping & self-referencing, by default.

## 4. Possible solution/workaround

First, create a eslint-resolver.cjs file and add contents:

```js
'use strict';
const { createRequire, builtinModules } = require('module');
exports.interfaceVersion = 2;
exports.resolve = function (source, file, config) {
  try {
    if (builtinModules.includes(source)) {
      return { found: true, path: null };
    }
    const myRequire = createRequire(file);
    const resolvedPath = myRequire.resolve(source);
    return { found: true, path: resolvedPath };
  } catch (err) {
    return { found: false };
  }
};

```

Then use it as import resolver in .eslintrc.js by adding:

```js
settings: {
    'import/resolver': {
      [path.resolve('./scripts/eslint-resolver.cjs')]: {},
    },
  },
```
> You may also need to import `path`, by adding `const path = require('path');` to top of file.

You can reproduce it via:

```bash
git checkout fix/exports-resolver
npm run lint
```

[View fix on github](https://github.com/Knorgias/demo-export-map/compare/master...fix/exports-resolver)
> Note: this fix only works in node (not in browser).

**Comment by ljharb** [comment] 2022-10-27 16:46
This plugin uses `resolve`, which does not yet support `exports` - and thus, doesn't support self-referencing. When it does, so will we.

Duplicate of #2430.

**Closed by ljharb** 2022-10-27 16:46 UTC

**Comment by ljharb** [comment] 2022-11-11 03:06
@toFrankie no, it's not supported yet.

Since packages *should* be using `exports` in a backwards-compatible way, this shouldn't be an obstacle, but if packages deviate from this best practice, it'll be annoying until `resolve` adds this support.

**Comment by daKmoR** [comment] 2022-11-16 15:54
I'm curious why is it using a custom-coded resolver when you could use the "built in" resolver from `node`?
e.g. why use the `resolve` package and not `require.resolve(source);`?

does eslint always run via node?

**Comment by ljharb** [comment] 2022-11-16 21:58
node's built-in resolver can't consistently be used in the way we need it; and regardless, having this plugin behave unpredictably across different node versions would be undesirable.
