### ISSUE TITLE
import/no-duplicates reports incorrectly for date-fns and date-fns/locales

### ISSUE THREAD

**Issue by Mikilll94** [import-js/eslint-plugin-import#2478] opened 2022-06-16 22:21 UTC
```
import { formatDuration } from "date-fns";
import { enGB, de, fr, it, es } from "date-fns/locale";
```

This code triggers `import/no-duplicates` error although `date-fns` and `date-fns/locale` are different modules so these imports cannot be combined.

**Comment by SQReder** [comment] 2022-07-01 11:12
Bump for this

**Comment by JounQin** [comment] 2022-07-19 20:13
duplicate of #1730 1479

**Closed by JounQin** 2022-07-19 20:13 UTC
Labels: bug, help wanted, typescript
