### ISSUE TITLE
import/no-unresolved error with 'node:' URLs (Node.js ESM)

### ISSUE THREAD

**Issue by cdauth** [import-js/eslint-plugin-import#2372] opened 2022-01-25 16:51 UTC
ECMAScript modules in Node.js support importing Node.js builtin modules using `node:` URLs (see the [documentation](https://nodejs.org/api/esm.html#node-imports)), for example:
```javascript
import fs from 'node:fs/promises';
```

Using such URLs causes eslint-plugin-import to raise an `import/no-unresolved` error.

**Comment by ljharb** [comment] 2022-01-25 17:13
What version of node are you using?

If you're seeing this error in your editor, then what version of node is your _editor_ using?

a) this plugin does not explicitly support native ESM, it expects transpiled ESM, which means that `import` is really `require`
b) `node:fs/promise` is only a core module for `require` in node `^14.18 || >= 16`.

**Comment by cdauth** [comment] 2022-01-25 17:28
I'm using Node.js v17.3.0. I'm assuming my editor (Code - OSS) is using the same.

It tested it and it actually seems that the error only shows up in the editor, but not when I run eslint from the command-line.

I didn't know that this plugin does not support native ESM. I'm using `@typescript-eslint/parser`, although I see the error both with TypeScript and with JavaScript files. In my `tsconfig.json` I have `"module": "esnext"` set, but maybe `@typescript-eslint/parser` ignores that and transpiles it to `require` anyways.

Maybe my eslint editor plugin is somehow misconfigured, although I don't know what setting it could be.

**Comment by ljharb** [comment] 2022-01-25 17:31
vscode has an embedded node, which i believe is v12.

The command line is the source of truth, so it's a problem you'll have to fix in your editor.

TS also isn't native ESM, it's a transpiler (which is better than native anyways).

**Comment by burtek** [comment] 2022-01-29 01:32
Just found out, in vscode one can set `"eslint.runtime"` setting to `"node"` to force eslint execution in locally installed version of node (see [explanation for this option here](https://github.com/microsoft/vscode-eslint#settings-options)). Requires full restart of vscode.

![image](https://user-images.githubusercontent.com/2940958/151642055-93f490dd-818c-416b-861c-164d6c115c5f.png)

**Comment by ljharb** [comment] 2022-01-29 01:58
Duplicate of #2035. Duplicate of #2248.

**Closed by ljharb** 2022-01-29 01:58 UTC
