### ISSUE TITLE
Proposal: New rule equivalent of import-name under microsoft contrib.

### ISSUE THREAD

**Issue by viditganpi** [import-js/eslint-plugin-import#2223] opened 2021-09-09 07:19 UTC
As, this is a suggested plugin under [typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin) for migrating some of the import rules from `TSLint` to `ESLint`, this rule will be a good addition to the repo. 
This rule is also used in `tslint-config-airbnb` refer [this](https://github.com/progre/tslint-config-airbnb/blob/master/tslint.js), which is used quite widely. This rule basically says that the import name should match the name of module being imported. 
I propose a similar rule be added to this plugin.

**Comment by ljharb** [comment] 2021-09-18 23:53
Duplicate of #325.

**Closed by ljharb** 2021-09-18 23:53 UTC
