### ISSUE TITLE
Status of upgrading to eslint v9?

### ISSUE THREAD

**Issue by StarManTheGamer** [import-js/eslint-plugin-import#3022] opened 2024-07-03 05:21 UTC
Hi, I use your plugin originally when I was on v8 but I'm wishing to upgrade to v9 and I noticed that your plugin is not supported. Is there a plan for this dependency to be upgraded to v9? Just curious. Thanks.

**Comment by steffen-4s1** [comment] 2024-07-03 11:30
See #2948

**Comment by ljharb** [comment] 2024-07-03 13:35
Duplicate of #2948.

**Closed by ljharb** 2024-07-03 13:35 UTC
