### ISSUE TITLE
TypeError: context.getScope is not a function

### ISSUE THREAD

**Issue by partynuts** [import-js/eslint-plugin-import#3025] opened 2024-07-04 14:08 UTC
I am already using the latest version of this plugin but it is not yet compatible with the latest version of eslint (9.6.0). So I have to use the workaround for the plugin to work.
Raising this here because it says to do so in the eslint docs: https://eslint.org/docs/latest/use/troubleshooting/v9-rule-api-changes

**Comment by ljharb** [comment] 2024-07-04 14:58
This plugin is not compatible yet with eslint v9, which means you can't upgrade yet, as the peer dep warnings should have told you when you tried to install them. Stick with v8 until this plugin supports v9.

Duplicate of #2948.

**Closed by ljharb** 2024-07-04 14:58 UTC
