### ISSUE TITLE
`no-unresolved` and `no-missing-require` rules report an error with glob@10.3.7

### ISSUE THREAD

**Issue by ddolcimascolo** [import-js/eslint-plugin-import#2883] opened 2023-09-25 07:29 UTC
Hello,

Cross-post from https://github.com/isaacs/node-glob/issues/557

I'm not sure which of the two libraries is responsible for this error, but node is happy to `require('glob')`, but `eslint-plugin-import` reports `no-unresolved` and `no-missing-require` violations...

Environment
* node@18.12.1
* eslint@8.50.0
* esltin-plugin-import@2.81.1
* glob@10.3.7

Anything I can do to help ?

Thanks,
David

**Comment by ljharb** [comment] 2023-09-25 10:39
https://github.com/isaacs/node-glob/issues/557#issuecomment-1733405748
> Looks like https://github.com/isaacs/node-glob/compare/v10.3.6...v10.3.7 switched to building with tshy, but since v10.3.6 has "main", and v10.3.7 does not have "main", that's potentially a breaking change in a patch version.
>
> An argument can be made that since `engines.node` is `>=16 || 14 >=14.17`, and all of those versions understand "exports" and don't need "main", that it's not breaking, but `eslint-plugin-import` doesn't yet understand "exports" (since `resolve` doesn't yet understand it), so that's what's causing the issue here.

For this plugin, that makes this a duplicate of #2703.

**Closed by ljharb** 2023-09-25 10:39 UTC
