### ISSUE TITLE
Support for package.json `exports` and `imports` ?

### ISSUE THREAD

**Issue by bradennapier** [import-js/eslint-plugin-import#1868] opened 2020-08-05 04:31 UTC
Sorry if this was posted, I did search quite a few things before posting :-P

So just came across this today, https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_packages - not sure how i missed it for so long but it appears that the internal `imports` mapping was just released in a recent `.x` version of v14.

Basically it allows node to resolve situations like Typescript `paths` would.  There are a few cases here that seem like they are fairly advanced to handle properly, and it doesn't seem like it works at the moment, although just initial testing so far.

While I know that there are [import resolvers that would allow defining the rules manually](https://www.npmjs.com/package/eslint-import-resolver-custom-alias), since this is an official node feature already launched in the LTS version of node, it probably makes sense to support it with the default node resolver?  
```json
{
"name": "example",
"type": "module",
"exports": {
    ".": "./src/index.js",
    "./quick": "./src/quick.js"
  },
  "imports": {
    "#alias": "./alias.js",
    "#tryPeer": ["some-peer-dep", "./src/peer-not-found.js"],
    "#conditionally": {
          "node": "./src/node.js",
          "require": "./src/required.js",
          "import": "./src/imported.js",
          "default": "./src/defaulted.js"
     }
  }
}
```

Given the above, I can run the following in node (no feature flags needed)

```javascript
// src/test.js

// loads src/quick.js due to exports "./quick" mapping pointing to "./src/quick.js"
import * as mods from 'example/quick'; 

// tries to load some-peer-dep package but if it fails it will load ./src/peer-not-found.js instead
import peer from '#tryPeer';

// if node env loads ./src/node, 
// if (not node) and required with require('example') loads ./src/required.js
// if (not node) and imported with import 'example' or import('example') loads ./src/imported.js
// if no match (dont think its possible here) , loads './src/defaulted.js'
import conditional from '#conditionally'

mods.runMain()
mods.runAlias()
```

```javascript
// src/quick.js
export * from '#alias'; // exports all modules from './alias.js' due to internal imports mapping for #alias
export * from 'example'; // exports all modules from './src/index.js' due to exports "." mapping to "./src/index.js"
```

```javascript
// src/index.js

export function runMain() {
   console.log('runs');
}
```

```javascript
// ./alias.js

export function runAlias() {
    console.log('alias runs')
}
```

> There is additional support for conditional handling which makes things a bit more complicated, but should potentially be considered.

> With the import maps I believe it also allows importing subpaths if supported so that if you have `#alias` resolve to `eslint` then you could do `import subpath from '#alias/lib/someFile.js'`

> I (think?) this is actually pretty similar to how `deno` handles module resolution mapping?

---

Running things with some flags to provide helper fns (no require.resolve by default) we do see:

```
 node --experimental-import-meta-resolve --experimental-top-level-await  ./src/test.js
```

```javascript
// src/test.js
console.log(
  await import.meta.resolve('example'),
  await import.meta.resolve('example/quick'),
  await import.meta.resolve('#alias'),
);
// file:///.../example/src/index.js 
// file:///.../example/src/quick.js 
// file:///.../example/alias.js
```

---

Also just realized this even works if not using `"type": "module"` for standard require-based modules, although with require.resolve it doesnt return file path:

```javascript
console.log(
  require.resolve('example'),
  require.resolve('example/quick'),
  require.resolve('#alias'),
);
// /.../example/src/index.js 
// /.../example/src/quick.js 
// /.../example/alias.js
```

**Comment by ljharb** [comment] 2020-08-05 05:35
Yes, both should be supported (altho "imports" is super brand new, like, less than a week).

However, support first needs to be added in `resolve` - which I'm the primary maintainer of - and I'm planning to work on that during the month of August. Once that's updated, adding the support here should be trivial.

**Comment by bradennapier** [comment] 2020-08-05 10:46
Awesome! Glad to hear it.  Thanks for the reply.  This issue can track its progress then!  

Look forward to it.

**Comment by clintwood** [comment] 2020-09-07 06:55
@ljharb any movement on this?

**Comment by ljharb** [comment] 2020-09-07 07:14
@clintwood not quite yet - https://github.com/browserify/resolve/pull/224 is still in progress, which would be the first step.

**Comment by clintwood** [comment] 2020-09-07 15:34
@ljharb - I see - thanks for the feedback!  Things have become a little complicated in nodeland 😉

**Comment by ctavan** [comment] 2020-10-02 14:23
@ljharb will the modifications to the `resolve` module also fix [package self references](https://nodejs.org/api/packages.html#packages_self_referencing_a_package_using_its_name) which make use of `pkg.exports` (they currently result in `import/no-extraneous-dependencies` errors)?

**Comment by ljharb** [comment] 2020-10-02 17:33
@ctavan once resolve supports that, yes.

**Comment by nfantone** [comment] 2021-01-14 17:07
Any workaround in the meantime? Getting `import/no-unresolved` errors on modules referenced by `"exports", currently.

Would defining custom aliases through `eslint-import-resolver-custom-alias` matching `"exports"` shape work?

**Comment by mattfysh** [comment] 2021-06-20 05:53
Best workaround is just to turn off the rule until they add support for routing via package.json `exports`/`imports` fields

**Comment by ljharb** [comment] 2021-06-20 14:48
A package that doesn’t provide equivalent CJS paths for exports paths isn’t back-compat and is thus being user-hostile, so this shouldn’t require workarounds most of the time.

**Comment by noahnu** [comment] 2021-06-20 15:58
> Best workaround is just to turn off the rule until they add support for routing via package.json `exports`/`imports` fields

If using Yarn Berry's PnP, you can use a custom resolver I wrote such as https://github.com/tophat/eslint-import-resolver-require (just delegates to require.resolve).

**Comment by mattfysh** [comment] 2021-06-20 23:07
> A package that doesn’t provide equivalent CJS paths for exports paths isn’t back-compat and is thus being user-hostile, so this shouldn’t require workarounds most of the time.

Not all packages are open source and made available for public consumption. In some closed development systems, a minimum version of nodejs is set allowing exclusive access to features such as subpath fields.

**Comment by ljharb** [comment] 2021-06-21 00:34
True enough. Unfortunately those will have to use the above resolver or wait until proper exports support is added to resolve.

**Comment by MikeG96** [comment] 2021-11-05 22:57
I'm using this in eslint rules file

```
   "import/no-unresolved": [2, { "ignore": ["^[#][\\w\\d]+$"] }]
```

**Comment by jrj2211** [comment] 2021-12-11 01:28
I'd just like to voice my support for this feature.

I had to modify @MikeG96's code to this to fully ignore these errors for imported modules with the # syntax:

```
"import/no-unresolved": [2, { "ignore": ["^#.+$"] }],
"import/extensions": 0
```

**Comment by ljharb** [comment] 2021-12-11 03:36
@jrj2211 voicing support is unnecessary; there is a 100% chance this feature will eventually be implemented.

**Comment by MuhammadSawalhy** [comment] 2022-02-18 08:21
> I'm using this in eslint rules file
> 
> ```
> "import/no-unresolved": [2, { "ignore": ["^#[\\w\\d\/\\-]+$"] }]
> ```

```
Oops! Something went wrong! :(

ESLint: 7.32.0

Error: .eslintrc.js:
        Configuration for rule "import/no-unresolved" is invalid:
        Value {} should be string.
```

**Comment by danielweck** [comment] 2022-02-23 00:30
Hi all, FYI I am successfully using this tiny ESLint import resolver to support ESM modules imports via package.json exports map:

https://gist.github.com/danielweck/cd63af8e9a8b3492abacc312af9f28fd

**Comment by ljharb** [comment] 2022-02-23 06:44
Indeed, duplicate of #1810.

**Closed by ljharb** 2022-02-23 06:44 UTC

**Comment by kellengreen** [comment] 2024-04-03 06:06
Was support for this added? I'm still seeing  `import/no-unresolved` when importing packages with `exports`.

**Comment by karlhorky** [comment] 2024-04-03 10:33
I think this is not yet completed, but has been moved to #1810

@ljharb, maybe the discussion in #1810 could be reopened to allow comments again?

**Comment by andyjy** [comment] 2024-07-16 14:07
> there are also multiple workarounds in that thread, including:
> - switching to eslint-import-resolver-typescript https://github.com/import-js/eslint-plugin-import/issues/1810#issuecomment-1189510672

May help others: the final piece I required to solve `Unable to resolve path to module` from `import/no-unresolved` when importing typescript with `eslint-import-resolver-typescript` from other packages within my monorepo was to ensure I had a `"default"` key as the last entry under `"exports"` in `package.json` of the referenced package.
