### ISSUE TITLE
Adding .js extension to import of .ts file results in error

### ISSUE THREAD

**Issue by richardkazuomiller** [import-js/eslint-plugin-import#2308] opened 2021-11-22 05:19 UTC
In order to build ESModules with TypeScript, we need to import our `.ts` files with a `.js` extension, like `./path/to/file.js`. If I enable eslint-plugin-import, it throws the error `Missing file extension "ts" for "./path/to/file.js"  import/extensions`. How do I configure eslint-plugin-import to allow me to import files the way they need to be imported in order to export valid ESM?

**Comment by ljharb** [comment] 2021-11-22 06:33
Duplicate of #2170.

**Closed by ljharb** 2021-11-22 06:33 UTC
