### ISSUE TITLE
Improve the way to find tsconfig.json

### ISSUE THREAD

**Issue by shiyangzhaoa** [import-js/eslint-plugin-import#2977] opened 2024-03-07 03:52 UTC
I have a monorepo project, and its structure looks like this:

```
monorepo
├── packages
│  ├── packageA
│  └── packageB
└── index.mjs
```

I want to run the `eslint` command in the root directory, like:

```js
const eslint = new ESLint({
    cwd: '/workspace/monorepo/packages/packageA',
    extensions: ['.ts', '.tsx', '.mts', '.cts'],
});

const result = await eslint.lintFiles('/workspace/monorepo/packages/packageA/index.ts');

console.log('result---', result);
```

The `eslint-plugin-import` plugin seems to be unable to find the `tsconfig.json` file of `packageA`:
<img width="695" alt="image" src="https://github.com/import-js/eslint-plugin-import/assets/19943129/40fdc66e-b9f5-449c-a76f-aa49a9f76bc8">

I think `eslint`’s cwd configuration should be used first, it looks like this:
```ts
const tsconfigInfo = tsConfigLoader({
    cwd: context.parserOptions && context.parserOptions.tsconfigRootDir || eslint.options.cwd || process.cwd(),
    getEnv: (key) => process.env[key],
});
```

## PS
At first I thought the `context` was the context configured by `eslint`, but later I found out that it was the plugin itself.
<img width="637" alt="image" src="https://github.com/import-js/eslint-plugin-import/assets/19943129/fb45a965-e245-40ea-8561-7189dfb4401b">

So I tried writing it like this and found that nothing worked 😅:
```ts
new ESLint({
    cwd: '/workspace/monorepo/packages/packageA',
    extensions: ['.ts', '.tsx', '.mts', '.cts'],
    overrideConfig: {
        parserOptions: {
            tsconfigRootDir: '/workspace/monorepo/packages/packageA'
         },
    },
})
```

**Comment by JounQin** [comment] 2024-03-07 06:12
Please stop doing this.

**Comment by JounQin** [comment] 2024-03-07 06:12
Duplicate of #274

**Closed by JounQin** 2024-03-07 06:12 UTC
