### ISSUE TITLE
ESLint: (TypeError: context.getScope is not a function)

### ISSUE THREAD

**Issue by shafaqkazmi** [import-js/eslint-plugin-import#3021] opened 2024-07-01 13:33 UTC
### What version of `eslint-plugin-import` are you using?
^2.29.1

### Environment
Operating System: MacOS 14.4.1
```
"engines": {
  "node": ">=14.18.0",
  "npm": ">=6.14.15"
},
"@nx/eslint": "19.3.2",
"@nx/eslint-plugin": "19.3.2",
"@typescript-eslint/eslint-plugin": "^7.14.1",
"@typescript-eslint/parser": "^7.14.1",
"eslint": "^9.6.0",
"eslint-config-airbnb": "^19.0.4",
"eslint-config-prettier": "^9.1.0",
"eslint-plugin-cypress": "3.3.0",
"eslint-plugin-import": "^2.29.1",
"eslint-plugin-jest": "28.6.0",
"eslint-plugin-jest-dom": "^5.4.0",
"eslint-plugin-jsx-a11y": "6.9.0",
"eslint-plugin-prettier": "^5.1.3",
"eslint-plugin-promise": "^6.4.0",
"eslint-plugin-react": "^7.34.3",
"eslint-plugin-react-hooks": "4.6.2",
"eslint-plugin-testing-library": "^6.2.2"
```

### What did you do?
Migrated `Nx` and other libraries to the latest version and running lint

### What actually happened?
Lint is broken with the below error. 

```js
> npx nx run shared-utils:lint --verbose
> nx run shared-utils:lint

Linting "shared-utils"...
NX   context.getScope is not a function

Occurred while linting /Users/frontends/libs/shared/utils/jest.config.js:1
Rule: "import/newline-after-import"

TypeError: context.getScope is not a function
Occurred while linting /Users/frontends/libs/shared/utils/jest.config.js:1
Rule: "import/newline-after-import"
    at ProgramExit (/Users/frontends/node_modules/eslint-plugin-import/lib/rules/newline-after-import.js:197:50)
    at ruleErrorHandler (/Users/frontends/node_modules/eslint/lib/linter/linter.js:1113:48)
    at /Users/frontends/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/frontends/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/frontends/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/frontends/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.leaveNode (/Users/frontends/node_modules/eslint/lib/linter/node-event-generator.js:349:14)
    at runRules (/Users/frontends/node_modules/eslint/lib/linter/linter.js:1159:40)
    at Linter._verifyWithoutProcessors (/Users/frontends/node_modules/eslint/lib/linter/linter.js:1440:31)
    at Linter._verifyWithConfigArray (/Users/frontends/node_modules/eslint/lib/linter/linter.js:2004:21)
    at Linter.verify (/Users/frontends/node_modules/eslint/lib/linter/linter.js:1528:61)
    at Linter.verifyAndFix (/Users/frontends/node_modules/eslint/lib/linter/linter.js:2295:29)
    at verifyText (/Users/frontends/node_modules/eslint/lib/cli-engine/cli-engine.js:265:48)
    at CLIEngine.executeOnFiles (/Users/frontends/node_modules/eslint/lib/cli-engine/cli-engine.js:845:28)
    at LegacyESLint.lintFiles (/Users/frontends/node_modules/eslint/lib/eslint/legacy-eslint.js:593:23)
    at run (/Users/frontends/node_modules/@nx/eslint/src/executors/lint/lint.impl.js:75:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async promiseToIterator (/frontends/node_modules/nx/src/command-line/run/run.js:33:11)
    at async getLastValueFromAsyncIterableIterator (/Users/frontends/node_modules/nx/src/utils/async-iterator.js:15:19)
    at async iteratorToProcessStatusCode (/Users/frontends/node_modules/nx/src/command-line/run/run.js:44:29)
    at async handleErrors (/Users/frontends/node_modules/nx/src/utils/params.js:9:24)
    at async process.<anonymous> (/Users/frontends/node_modules/nx/bin/run-executor.js:59:28)
 ```

### Additional Notes
ESLint v9.0.0 introduces [changes to the rules API](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/) that plugin rules use, which included moving some methods from the context object to the sourceCode object. I

https://eslint.org/docs/latest/use/troubleshooting/v9-rule-api-changes

**Comment by ljharb** [comment] 2024-07-01 16:00
This plugin isn't yet compatible with eslint 9, so you simply can't upgrade yet if you want to use the plugin (our peerDependencies declaration should have caused npm to refuse to install both in the same graph)

Duplicate of #2948.

**Closed by ljharb** 2024-07-01 16:00 UTC
