### ISSUE TITLE
`no-extraneous-dependencies` causes errors for not imported `@types/*` 

### ISSUE THREAD

**Issue by alan-albuquerque** [import-js/eslint-plugin-import#2168] opened 2021-07-28 15:50 UTC
Hello I'am facing a similar issue reported [here](https://github.com/import-js/eslint-plugin-import/issues/2078) and there @ljharb asked to open another issue if it is still happening on version `2.23.4`.

My scenario is:
node: v12.22.1

```js
import { difference } from 'ramda';
import { v4 as uuid } from 'uuid';
```
causes:
```
  error  '@types/uuid' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  error  '@types/ramda' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
```

package.json
```
"eslint": "^7.31.0",
"eslint-plugin-import": "2.23.4",
```

config:
```
"import/no-extraneous-dependencies": [
            "error",
            {
                "devDependencies": ["**/*.d.ts", "**/*.test.*", "**/*.spec.*", "test-utils/**/*"]
            }
        ]
```

Am I doing something wrong?

**Comment by JounQin** [comment] 2022-07-19 19:08
Can you provide a reproduction?

**Comment by DonIsaac** [comment] 2023-06-28 17:20
I'm seeing this problem as well. My config is simlar, and my versions are below:

- `eslint-plugin-import`:  2.27.5
- `eslint-plugin-import-resolver-typescript` : `2.23.5`
- `typescript`: 5.0.4
- `typescript-eslint/parser`: 5.48.0

**Comment by AndyOGo** [comment] 2023-08-21 19:02
I have the same problem with packages from `@types/*`, e.g. `@types/react`.

```ts
import { useEffect, useState } from "react";
```

> '@types/react' should be listed in the project's dependencies, not devDependencies.eslint[import/no-extraneous-dependencies](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-extraneous-dependencies.md)

**Comment by AndyOGo** [comment] 2023-08-21 19:16
It seems that `getModuleRealName()` causes the issue of intepreting any import of `react` as `@types/react`.

 https://github.com/import-js/eslint-plugin-import/blob/6b95a021938139726b3f862beb37012d6e2afab2/src/rules/no-extraneous-dependencies.js#L213C27-L213C44

**Comment by ahuth** [comment] 2024-01-12 18:51
I think https://github.com/import-js/eslint-import-resolver-typescript/issues/265 may be the cause of this

**Comment by JounQin** [comment] 2024-01-12 23:34
Duplicate of https://github.com/import-js/eslint-import-resolver-typescript/issues/265

**Closed** 2024-01-12 23:35 UTC
Labels: help wanted, typescript

**Comment by JounQin** [comment] 2024-01-17 15:44
Please follow the README more carefully:

https://github.com/import-js/eslint-plugin-import#typescript

See also https://github.com/import-js/eslint-plugin-import/blob/7a21f7e10f18c04473faadca94928af6b8e28009/config/typescript.js#L17

**Comment by ljharb** [comment] 2024-01-17 16:10
More generally, please use the `config/typescript` config from this plugin, which sets that.
