### ISSUE TITLE
`node:`-prefixed modules not recognised as `builtin`s

### ISSUE THREAD

**Issue by burtek** [import-js/eslint-plugin-import#2377] opened 2022-01-29 00:59 UTC
`node:`-prefixed modules are not recognised as `builtin`s

![image](https://user-images.githubusercontent.com/2940958/151640309-8552c11f-c00a-4d64-a58d-b0f39b517060.png)
![image](https://user-images.githubusercontent.com/2940958/151640314-6c88b124-f51c-4d26-a9d2-f0eba8536822.png)

Latest `eslint` (8.8.0) and latest `eslint-plugin-import` (2.25.4)

**Comment by ljharb** [comment] 2022-01-29 01:01
That's because a) you're using it in vscode and not the command line - only the command line is the source of truth; and b) vscode bundles node 14.16, and `node:` support was added in 14.18.

Either way, I'd suggest avoiding use of the `node:` prefix, since it adds zero value.

Duplicate of #2373.

**Closed by ljharb** 2022-01-29 01:01 UTC

**Comment by burtek** [comment] 2022-01-29 01:32
Just found out, in vscode one can set `"eslint.runtime"` setting to `"node"` to force eslint execution in locally installed version of node (see [explanation for this option here](https://github.com/microsoft/vscode-eslint#settings-options)). Requires full restart of vscode.

![image](https://user-images.githubusercontent.com/2940958/151642055-93f490dd-818c-416b-861c-164d6c115c5f.png)

**Comment by IanVS** [comment] 2022-05-18 18:18
>Either way, I'd suggest avoiding use of the node: prefix, since it adds zero value.

I just had a bug where https://www.npmjs.com/package/url was being used rather than the node builtin `url`.  Changing to `node:url` fixed that bug.  So, I don't think it has zero value.  I was coming here to look for a rule that enforced its use, but it sounds like you'd be against that, so I'll look elsewhere.

**Comment by ljharb** [comment] 2022-05-18 18:38
@IanVS that doesn't make sense; in any node version where `url` is built in, it can't possibly use the installed one.

**Comment by IanVS** [comment] 2022-05-18 18:43
My guess is that it was due to vite choosing to use the dependency during bundling.  I didn't look too deeply.  Maybe it's a bundler error, but it was easily worked around by being explicit in my import statement.

**Comment by ljharb** [comment] 2022-05-18 18:45
Yes, that does indeed seem like a bundler issue.
