### ISSUE TITLE
Error: Failed to load plugin 'import' declared in '.eslintrc': Cannot find module 'typescript/package.json' 2.27.0

### ISSUE THREAD

**Issue by DerekWW** [import-js/eslint-plugin-import#2665] opened 2023-01-12 00:42 UTC
Lint jobs suddenly started failing with the following:
```
Error: Failed to load plugin 'import' declared in '.eslintrc': Cannot find module 'typescript/package.json'
```
After some digging it appears that 2.27.0  of eslint-plugin-import is breaking my pipeline. I have pinned to 2.26.0 and that has solved my issue. I have not investigated what the root cause may have been.

Node: 14.15.4
ESlint: 7.32.0

**Comment by davidrunger** [comment] 2023-01-12 01:07
This is a dupe of this issue: https://github.com/import-js/eslint-plugin-import/issues/2663.

**Comment by ljharb** [comment] 2023-01-12 01:13
I'm not sure why `typescript/package.json` wouldn't be findable.

**Comment by ljharb** [comment] 2023-01-12 03:36
v2.27.1 is released, but I'm not sure if that fixes this problem or not.

**Comment by ljharb** [comment] 2023-01-12 03:37
ah, found it - this was caused by #2475. I'll have a fix ready and released shortly.

**Closed** 2023-01-12 03:43 UTC

**Comment by ljharb** [comment] 2023-01-12 03:47
v2.27.2 is released.

**Comment by DerekWW** [comment] 2023-01-12 04:02
Thanks so much!

**Comment by matthew-charles-chan** [comment] 2023-01-12 17:26
Thank you for the quick fix and release!

**Comment by norayr93** [comment] 2024-02-17 04:57
It's still broken in 2.29.x version

**Comment by ljharb** [comment] 2024-02-17 05:19
@norayr93 please file a new issue, then
