### ISSUE TITLE
ESM: Unable to resolve path to module 'got'  import/no-unresolved

### ISSUE THREAD

**Issue by mahnunchik** [import-js/eslint-plugin-import#2331] opened 2021-12-18 18:43 UTC
Unable to resolve path to module 'got'  import/no-unresolved

```js
// Unable to resolve path to module 'got'  import/no-unresolved
import got from 'got';
```

* got v12.0.0
* eslint v8.5.0
* eslint-plugin-import 2.25.3

**Comment by ljharb** [comment] 2021-12-19 02:49
Do you have it installed? Are you getting that warning on the command line, or just in your editor? Is eslint installed locally, and not globally?

**Comment by mahnunchik** [comment] 2021-12-19 06:17
```json
"dependencies": {
    "got": "^12.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.16.5",
    "@babel/eslint-parser": "^7.16.5",
    "eslint": "^8.5.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-import": "^2.25.3"
  },
"eslintConfig": {
    "parser": "@babel/eslint-parser",
    "extends": [
      "airbnb-base"
    ],
    "parserOptions": {
      "ecmaVersion": 2021,
      "requireConfigFile": false
    }
  }
```

**Comment by ljharb** [comment] 2021-12-19 14:48
Thanks, but that doesn’t answer my questions. Resolving requires everything be present in node_modules.

**Comment by mahnunchik** [comment] 2021-12-19 15:43
> Do you have it installed?

Yes

> Are you getting that warning on the command line, or just in your editor?

Comandline and editor (vs code).

> Is eslint installed locally, and not globally?

Locally, fresh install.

**Comment by ljharb** [comment] 2021-12-19 16:07
Thanks!

In this case, the latest version of got drops support for CJS, and as such, can’t be resolved by our CJS-only resolution mechanism. If you’re using native ESM, this plugin won’t help you, because it’s designed for use with CJS,  or transpiled ESM (Babel/TS).

If you downgrade to got v11, or switch to a package author that isn’t user-hostile, then you should see everything resolve correctly.

**Comment by mahnunchik** [comment] 2021-12-19 16:29
ESM should work. CJS should be deprecated.

**Comment by ljharb** [comment] 2021-12-19 16:35
That’s a strong and wildly incorrect opinion.

Native ESM has tons of downsides and offers no benefits over CJS. Both are first-class module systems in node, so yes, native ESM should work, but the ecosystem isn’t ready to support it yet.

I’m going to close this.

**Closed by ljharb** 2021-12-19 16:35 UTC

**Comment by nghiepit** [comment] 2021-12-21 23:54
Same issue with `type-fest`

```ts
import {Except} from 'type-fest';
```
>Unable to resolve path to module 'type-fest'.eslintimport/no-unresolved

**Comment by ljharb** [comment] 2021-12-22 03:59
Same problem, caused by the same maintainer - altho in that case, it doesn't have any runtime values, so you should be using `import type`.

**Comment by jsg2021** [comment] 2022-01-05 23:03
Those modules that the `no-unresolved` rule fails to find appear to be missing `main` and only defining `exports` (as node documents).

**Comment by ljharb** [comment] 2022-01-05 23:04
@jsg2021 yes, see https://github.com/import-js/eslint-plugin-import/issues/2331#issuecomment-997417550

**Comment by jsg2021** [comment] 2022-01-05 23:09
@ljharb sorry :} I was just deep in my own research trying to assist my finding. Forgot to double-check the thread. I've been lucky that I'm only now having to sort with these modules.

**Comment by silverwind** [comment] 2022-09-09 12:49
I made a repro for this issue: https://github.com/silverwind/import-got

```bash
git clone https://github.com/silverwind/import-got.git
cd import-got
npm i && npm t
```

It seems there is a unresolvable situation where the package authors indirectly [blames](https://github.com/sindresorhus/got/releases/tag/v12.0.0) this module:

> Pretty much any problem with loading this package is a problem with your bundler, test framework, etc, not Got.

But https://github.com/import-js/eslint-plugin-import/issues/2331#issuecomment-997417550 blames the module, so we come full cycle.

Is there any resolution in sight?

**Comment by jsg2021** [comment] 2022-09-09 13:03
> I made a repro for this issue: https://github.com/silverwind/import-got
> 
> 
> 
> ```bash
> 
> git clone https://github.com/silverwind/import-got.git
> 
> cd import-got
> 
> npm i && npm t
> 
> ```
> 
> 
> 
> It seems there is a unresolvable situation where the package authors indirectly [blames](https://github.com/sindresorhus/got/releases/tag/v12.0.0) this module:
> 
> 
> 
> > Pretty much any problem with loading this package is a problem with your bundler, test framework, etc, not Got.
> 
> 
> 
> But https://github.com/import-js/eslint-plugin-import/issues/2331#issuecomment-997417550 blames the module, so we come full cycle.
> 
> 
> 
> Is there any resolution in sight? Maybe @szmarczak can comment what the problem is with `got`'s exports.


[that comment](https://github.com/import-js/eslint-plugin-import/issues/2331#issuecomment-997417550) answered your question? Pure esm packages do not need this rule. Turn it off?

**Comment by jsg2021** [comment] 2022-09-09 14:08
idk, but inspecting `got`... it has no "main" entry point (commonjs) and only an "exports" entry (esm) and no alt ("module"/"es:next"/etc) entry points... and the linked comment suggests the resolution algorithm only works for those commonjs/alt entry points. 🤷 just my understanding... i'm not a maintainer, just another user like you.

**Comment by silverwind** [comment] 2022-09-09 14:12
Just guessing, but maybe it's because `got` has no `index.js`. For example another pure ESM module, https://github.com/sindresorhus/is-ip, is resolved fine by this plugin and it has a `index.js`.

**Comment by JounQin** [comment] 2022-09-09 14:39
So it's still related to `exports` field support, right?

**Comment by silverwind** [comment] 2022-09-09 14:49
Yes, ultimately, the issue is that `eslint-plugin-import` does not seem to parse `exports`.

Interestingly, `require.resolve` which should be a CJS mechanism is till able to resolve the package correctly:

```
> require.resolve("got")
'/Users/silverwind/git/import-got/node_modules/got/dist/source/index.js'
> require.resolve("is-ip")
'/Users/silverwind/git/import-got/node_modules/is-ip/index.js'
```

Maybe `eslint-plugin-import` should just use `require.resolve` to fix this issue.

**Comment by ljharb** [comment] 2022-09-09 15:01
Again, ESM-only packages are the problem - this plugin supports *transpiled* ESM, and not native ESM. is-ip *seems* to work because the index.js and lack of main means pre-exports node would try and fail to load that file.

When `resolve` gains support for “exports”, it will support native ESM too.

**Comment by silverwind** [comment] 2022-09-09 15:07
For some cases like a default import, it might be enough to just see if the request resolves to a file, without actually parsing it.

I'm pretty sure there is some bug in [resolve.js](https://github.com/import-js/eslint-plugin-import/blob/main/utils/resolve.js) where the code path does not end up in `require.resolve` with which it may have worked, but I think I'll just wait for actual ESM support instead of chasing this further :)

**Comment by ljharb** [comment] 2022-09-09 15:12
It is a very explicit and intentional choice to avoid using the built-in require.resolve.
