### ISSUE TITLE
`imported multiple times` error breaks code on format

### ISSUE THREAD

**Issue by seanlail** [import-js/eslint-plugin-import#2848] opened 2023-08-04 08:32 UTC
I have a Svelte component with this code:
```svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { spring } from 'svelte/motion';
```

### The issue

I see this error in VSCode and when I run eslint:
```bash
  2:41  warning  '/Users/.../node_modules/svelte/types/index.d.ts' imported multiple times  import/no-duplicates
  3:24  warning  '/Users/.../node_modules/svelte/types/index.d.ts' imported multiple times  import/no-duplicates
```

When I save the file (I have formatOnSave enabled) it moves the `spring` import to the wrong module and breaks the build:
```svelte
<script lang="ts">
  import { onMount, spring } from "svelte";
```

### Link to **GitHub Repo** with Minimal Reproducible Example

https://github.com/seanlail/lint-issue-556

Last commit shows the issue.
If you run this locally, remove [the comment here](https://github.com/seanlail/lint-issue-556/commit/b7d4f2d5276f163a2961c8986ee38301d1086006) and you will see the issue.

### Versions

eslint: 8.46.0
eslint-import-resolver-typescript: 3.5.5
eslint-plugin-import: 2.28.0
eslint-plugin-svelte: 2.32.4
npm: 9.5.0
node: v18.14.2
svelte: 4.1.2
typescript: 5.1.6

### Related

I created this issue in the `eslint-plugin-svelte` repo but have been advised the issue is with `eslint-plugin-import`:
https://github.com/sveltejs/eslint-plugin-svelte/issues/556

**Comment by JounQin** [comment] 2023-08-04 08:36
duplicate of #1479

**Closed by JounQin** 2023-08-04 08:36 UTC
