### ISSUE TITLE
'TypeError: context.getAncestors is not a function' with ESLint v9

### ISSUE THREAD

**Issue by vpmedia** [import-js/eslint-plugin-import#2995] opened 2024-04-06 09:32 UTC
After upgrading to ESLint v9 I'm getting the following exception:

```
TypeError: context.getAncestors is not a function
Occurred while linting PROJECT_DIR/eslint.config.js:1
Rule: "import/no-named-as-default"
    at importDeclaration (PROJECT_DIR/node_modules/eslint-plugin-import/lib/importDeclaration.js:2:27)
    at checkDefault (PROJECT_DIR/node_modules/eslint-plugin-import/lib/rules/no-named-as-default.js:21:62)
    at ruleErrorHandler (PROJECT_DIR/node_modules/eslint/lib/linter/linter.js:1145:48)
    at PROJECT_DIR/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (PROJECT_DIR/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (PROJECT_DIR/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (PROJECT_DIR/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (PROJECT_DIR/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at runRules (PROJECT_DIR/node_modules/eslint/lib/linter/linter.js:1184:40)

```

**Comment by RobinTail** [comment] 2024-04-06 10:15
https://github.com/import-js/eslint-plugin-import/blob/8587c85a60ccb3839cb2eabe50cf098a4a2c03c2/package.json#L104

Compatibility issue: https://github.com/import-js/eslint-plugin-import/issues/2948

**Comment by sergeushenecz** [comment] 2024-04-06 11:02
is it package will upgrade or no?

**Comment by ljharb** [comment] 2024-04-06 14:49
Just like with every eslint major, you basically always have to wait weeks or months to upgrade to it, until all the plugins and configs you depend on have had a chance to do so.

Closing as a duplicate of #2948. Thanks for the stack trace - that will help the effort to add compatibility.

**Closed by ljharb** 2024-04-06 14:49 UTC

**Comment by cameronmurphy** [comment] 2024-09-23 11:37
I'm experiencing this exact stack trace with ESLint 9.11.0 and eslint-plugin-import 2.30.0 and I'm following the doco [here](https://github.com/import-js/eslint-plugin-import?tab=readme-ov-file#config---flat-eslintconfigjs)

I can't comment on the broader ESLint v9 issue as it's locked.

**Comment by ljharb** [comment] 2024-09-23 16:00
@cameronmurphy the eslint 9 issue being still open means we don't support eslint 9 yet, so you simply can't use it with this plugin yet. Stick to eslint 8 for now.

**Comment by ljharb** [comment] 2025-04-01 20:55
eslint 9 works with this plugin already. The only caveat is the no-unused-modules rule, which requires an empty .eslintrc at the root if you're using flat config.
