### ISSUE TITLE
New release version

### ISSUE THREAD

**Issue by Valen-Pony** [import-js/eslint-plugin-import#2571] opened 2022-10-14 07:09 UTC
The latest version in npm is 2.26.0, which is released 6 monthes ago and many new featrues in the readme is not released.
When will new release be published?

**Comment by ljharb** [comment] 2022-10-14 20:07
There's no timeline for releases. Check documentation for the tagged release you're using instead of master/main.

Duplicate of #2539. Duplicate of #2567.

**Closed by ljharb** 2022-10-14 20:07 UTC
