### ISSUE TITLE
Compatibility with ESLint 9.x

### ISSUE THREAD

**Issue by TylerVigario** [import-js/eslint-plugin-import#3002] opened 2024-04-15 23:30 UTC
```sh
npm update  
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: n2words@1.20.0
npm ERR! Found: eslint@9.0.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^9.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
npm ERR! node_modules/eslint-plugin-import
npm ERR!   dev eslint-plugin-import@"^2.29.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! NUNYA\AppData\Local\npm-cache\_logs\2024-04-15T23_28_49_465Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: NUNYA\AppData\Local\npm-cache\_logs\2024-04-15T23_28_49_465Z-debug-0.log
```

**Comment by ljharb** [comment] 2024-04-15 23:41
The peer deps clearly state that eslint 9 is not yet supported, so you can't upgrade to it yet.

Duplicate of #2948.

**Closed by ljharb** 2024-04-15 23:41 UTC

**Comment by TylerVigario** [comment] 2024-04-15 23:42
Shoot, I didn't see that for some reason. Thanks for pointing it out.
