### ISSUE TITLE
ESlint^9 causes an error when importing typescript-eslint with pnpm

### ISSUE THREAD

**Issue by lnuvy** [import-js/eslint-plugin-import#3123] opened 2024-12-20 06:33 UTC
Hello,

I am using eslint-plugin-import with flatConfig.
Even in projects using Yarn, the following warning was displayed:
```
Could not find a declaration file for module 'eslint-plugin-import'. '/{project_path}/node_modules/eslint-plugin-import/lib/index.js' implicitly has an 'any' type.
```

But, this issue seems to directly affect the `typescript-eslint` package, causing an error in pnpm projects.

I am sharing screenshots and a test repository below.

[Link](https://github.com/lnuvy/eslint9-eslint-plugin-import)

![Image](https://github.com/user-attachments/assets/66152932-a91e-4483-a572-75089691d1c4)
unused import-plugin

![Image](https://github.com/user-attachments/assets/b1ab6d81-edb1-42ba-a614-fb0a9522df4f)
![Image](https://github.com/user-attachments/assets/250b9adf-383b-4cbf-b55f-8db1eadb193f)

Even after trying various versions of TypeScript, ESLint, and typescript-eslint, the error consistently occurs only in pnpm projects.

+ Despite the error, everything works fine.

I sincerely apologize if I missed a duplicate issue or an existing solution.
Thanks!

**Comment by ljharb** [comment] 2024-12-20 07:01
That error is a TypeScript error. This package doesn't export its own types, so either you have to install a DT package, or, manually define them yourself.

If the issue is with typescript-eslint, then you've filed this on the wrong repo.

**Comment by michaelfaith** [comment] 2024-12-20 09:23
I believe the issue with resolve on `typescript-eslint` is that the package doesn't have a `main` and exclusively leverages export conditions, which the node resolver doesn't currently support.  

As far as types go, weren't those added recently?  I thought I saw GRath putting that in.

**Comment by lnuvy** [comment] 2024-12-20 10:40
@michaelfaith 
Oh, I hadn't checked `index.d.ts` before. I was considering contributing to the DefinitelyTyped.. 🥲

Then It seems that the current issue is `index.d.ts` is not being properly exported.
Even in a Yarn package, type warnings appeared. As a temporary workaround, I handled it like this, and the warnings no longer showed up:

```
import { ESLint, Linter } from "eslint";

declare const eslintPluginImport: ESLint.Plugin & {
  configs: {
    recommended: Linter.LegacyConfig;
    errors: Linter.LegacyConfig;
    warnings: Linter.LegacyConfig;
    typescript: Linter.LegacyConfig;
  };
  flatConfigs: {
    recommended: Linter.Config;
  };
};

export = eslintPluginImport;
```

**Comment by michaelfaith** [comment] 2024-12-20 14:15
Ah, it looks like the types change hasn't been released yet.  Merged but not in a release.  So, you should be able to remove that workaround after the release is cut: https://github.com/import-js/eslint-plugin-import/blob/main/CHANGELOG.md#unreleased

**Comment by lnuvy** [comment] 2024-12-21 07:29
Thank you for your help!

But another problem remains: The error persists only in pnpm projects on the line `import tseslint from "typescript-eslint"`, and seems to be influenced by importing `eslint-plugin-import`. (This error persists even after I created a `index.d.ts` file.)

I don’t believe this is an issue with `typescript-eslint`.

Could it be something I misconfigured? Or, if this is an issue caused by pnpm's symbolic links, how can it be resolved?

**Comment by ljharb** [comment] 2024-12-21 08:22
If you're importing typescript-eslint, that's where the problem lies.

**Comment by lnuvy** [comment] 2024-12-21 09:14
I found the exact cause today.

When using the `tseslint.config()` function from `eslint-typescript`, `eslint-plugin-import` must be declared inside `extends` array rather than being declared parameter.

```diff
import tseslint from "typescript-eslint"
import importPlugin from "eslint-plugin-import"

export default tseslint.config(
  // other configs...
  ...
- importPlugin.flatConfigs.recommended,
+ {
+   files: ["**/*.{ts,tsx}"],
+   extends: [importPlugin.flatConfigs.recommended],
+   // other configs...
+ }
```

The kind of package manager didn't matter.

https://github.com/user-attachments/assets/22809e6e-467f-41e2-8b88-9aaa7b211ec7

**Closed** 2024-12-21 15:44 UTC
