### ISSUE TITLE
`no-cycle` hangs since v2.23.0

### ISSUE THREAD

**Issue by alumni** [import-js/eslint-plugin-import#2076] opened 2021-05-15 10:03 UTC
With both v2.23.0 and v2.23.1, running `eslint` on the entire project hangs. Also, it will make vscode eslint plugin hang as well when saving a file (with fix on save enabled).

`.eslintrc`:
```jsonc
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "tsconfig.json"
  },
  "rules": {
    "import/no-cycle": ["error", { "ignoreExternal": true, "maxDepth": 7 }]
  },
  "settings": {
    "import/parsers": {
      "@typescript-eslint/parser": [".ts", ".tsx"]
    },
    "import/resolver": {
      "typescript": {
        "project": "tsconfig.json"
      }
    }
  }
}
```
`tsconfig.json`:
```jsonc
{
    "compilerOptions": {
        "paths": {
            "@common": ["src/app/common"],
        }
    }
}
```

**Comment by ljharb** [comment] 2021-05-15 15:49
I suspect this might be due to #2077, but I'll leave this open pending confirmation that it's still an issue with v0.23.2 (not yet released).

Either way, does the issue still occur with `no-cycle` disabled?

**Comment by alumni** [comment] 2021-05-16 13:55
> Either way, does the issue still occur with no-cycle disabled?

It's fine with `no-cycle` disabled. We had it anyway disabled in the pre-commit hook to speed things up.

In v2.32.2 `eslint --rule 'import/no-cycle: 0'` will finish in a reasonable amount of time (without cache <1min), but simply running `eslint` will not finish even after 10min.

**Comment by ljharb** [comment] 2021-05-21 18:59
Does it hang running on the CLI, or only in vscode?

**Comment by alumni** [comment] 2021-05-21 19:51
As mentioned above, both the `eslint` cli and the vscode extension hang. What I noticed:
* `eslint` cli hangs when run for the entire project
* `eslint` cli doesn't hang when `no-cycle` is disabled
* vscode doesn't hang when a single file is opened (might be a bit slower than before though, not sure if it felt faster before because of caching)
* vscode hangs when a file is saved and fix on save is enabled

**Comment by saharrachamimfg** [comment] 2021-05-30 13:43
This is a critical issue. Can we please fix or revert?

**Comment by SRachamim** [comment] 2021-05-30 13:44
This is a critical issue. Can we please fix or revert?

**Comment by ljharb** [comment] 2021-05-30 15:47
Does this still occur with v2.23.4?

I’d love to fix it, but without a repro repo, it’s very difficult to debug.

**Comment by alumni** [comment] 2021-05-30 22:08
Haven't checked 2.23.4 yet, but the issue was still present in 2.23.3.

**Comment by ezpuzz** [comment] 2021-06-16 14:29
Also having issue.  Eslint hangs after printing warnings and errors.

**Comment by nicolashenry** [comment] 2021-06-18 09:11
It seems that on one of my project the `import/no-cycle` rule takes around 30 minutes to run with 2.23.4 (if I keep only `"import/no-cycle": ["warn", { "ignoreExternal": true }]`). It was really faster before on 2.22.1, around 3 minutes to run (note that it was already the slowest rule in my configuration).

**Comment by SRachamim** [comment] 2021-06-27 10:22
> Does this still occur with v2.23.4?
> 
> I’d love to fix it, but without a repro repo, it’s very difficult to debug.

Yes. I can't publish my repo, and can't really reproduce it outside my repo. But it works well on on 2.22.1 and below. We're actually stuck on this version.

**Comment by alumni** [comment] 2021-08-10 13:35
Possibly related to #1408.

Running `eslint --debug` would output for each file:
```
eslintrc:ignore-pattern Check {
    filePath: '<ROOT>\\<PATH>\\<FILE>',
    dot: false,
    relativePath: '<PATH>/<FILE>',
    result: false
} +6s
eslint:file-enumerator Yield: <FILE> +6s
eslintrc:cascading-config-array-factory Load config files for <ROOT>\<PATH>. +6s     
eslintrc:cascading-config-array-factory Cache hit: <ROOT>\<PATH>. +0ms
eslint:cli-engine Lint <ROOT>\<PATH>\<FILE> +6s
eslint:linter Linting code for <ROOT>\<PATH>\<FILE> (pass 1) +5ms 
eslint:linter Verify +0ms
eslint:linter With ConfigArray: <ROOT>\<PATH>\<FILE> +0ms
```
And after a long pause:
```
eslint:linter Generating fixed text for <ROOT>\<PATH>\<FILE> (pass 1) +7s
eslint:source-code-fixer Applying fixes +7s
eslint:source-code-fixer shouldFix parameter was false, not attempting fixes +0ms
```

**Comment by walkerburgin** [comment] 2021-10-01 00:37
We recently tried to upgrade a large codebase from `v2.22.1` to `2.24.2` and saw our lint time jump from ~30 seconds to ~14 minutes. 

After profiling, it looks like almost all of the time is being spent [here](https://github.com/import-js/eslint-plugin-import/blob/dd814245b7f769a84235f2ffb7204287d47001ba/src/rules/no-cycle.js#L45-L50):  

![image](https://user-images.githubusercontent.com/1189357/135547920-34c2f922-8c4b-4e3b-8a16-9f2d51ea5fd5.png)

And if I change our config from this:

```js
"import/no-cycle": [
    "error",
    {
        ignoreExternal: true,
        maxDepth: 2,
    },
],
```

to this: 

```js
"import/no-cycle": [
    "error",
    {
        ignoreExternal: false,
        maxDepth: 2,
    },
],
```

Short circuiting the call to `resolve()` [here](https://github.com/import-js/eslint-plugin-import/blob/dd814245b7f769a84235f2ffb7204287d47001ba/src/rules/no-cycle.js#L48), the performance improves significantly. 

We similarly can't publish the codebase, but I'd be happy to test out any proposed changes and report back.

**Comment by ljharb** [comment] 2021-10-01 02:28
@walkerburgin thanks, that's very helpful. is there any chance you could confirm on your codebase what the value of `name` and `context.getPhysicalFilename()` are at the time `resolve` is called there? In particular, I'm wondering if there's an excessive number of repeated calls, such that there'd be a performance win from memoizing that result.

**Comment by walkerburgin** [comment] 2021-10-01 16:27
@ljharb I logged this out to the console and then counted duplicates in the output: 

```js
console.log("" + name + "@" + context.getPhysicalFilename());
```

Here were the top 10 counts (I dropped the context file names): 

```
    184 lodash-es@...
    149 lodash-es@...
    135 lodash-es@...
    117 lodash-es@...
    115 reselect@...
    103 lodash-es@...
     98 lodash-es@...
     87 lodash-es@...
     83 lodash-es@...
     82 react@...
```

There were 384,783 unique calls, the max count was 184, and the median was 1.  

If I drop the context file path and just log out the name I get 6,103 unique calls, a max count of 8,741, and a median count of 32. 

```
  8741 lodash-es
   4859 reselect
   4695 redoodle
```

**Comment by ljharb** [comment] 2021-10-01 16:29
I suspect the filename is required, because of the potential for repeated dependencies, but that does suggest that memoizing based on both would provide _some_ improvement.

**Comment by styu** [comment] 2022-01-12 18:31
any update here? In trying to upgrade to ESLint 8 internally, it looks like the first version of this plugin that supports ESLint 8 is 2.23.0, but because of this issue we are unable to upgrade.

**Comment by ljharb** [comment] 2022-01-12 18:42
@styu no, there's no update, or it'd be posted on the issue, like everywhere on github.

I'd be happy to review a PR that included the memoization mentioned [here](https://github.com/import-js/eslint-plugin-import/issues/2076#issuecomment-932376901).

**Comment by alumni** [comment] 2022-01-13 08:24
@styu if you need to update eslint quickly, you disable the `no-cycle` rule, upgrade the import plugin if you're using other rules (there were some breaking changes with the import order for me) and use external tools instead. I was actually using [madge](https://github.com/pahen/madge) for cycle detection before replacing it with `no-cycle` and now I switched to [dependency-cruiser](https://github.com/sverweij/dependency-cruiser) (2x-3x slower than madge but I think I had other issues with madge).

**Comment by alumni** [comment] 2022-01-14 11:19
@ljharb madge is using [dependency-tree](https://github.com/dependents/node-dependency-tree), which does its own memoization (the `visited` property): https://github.com/pahen/madge/blob/aa49a0a94fd966be25141c92c75f97d90ad73dc6/lib/tree.js#L109

I'm not sure things like `captureJsDoc` would be possible with it. I'm also not sure what would be the effect in case of different configurations (typescript/babel/swc/esbuild/webpack etc.). Maybe the option you suggested initially would be better, to improve the memoization in ExportMap 🤷🏻‍♂️

**Comment by Rogdham** [comment] 2022-01-28 22:08
For what it's worth, applying some simple caching (patch below) top of v2.25.4 makes quite a difference. There are probably some unexpected side-effects though.

Timing measured with `TIMING=1 yarn eslint ...` for the `no-cycle` rule on a private repo:
 - without patch: did not finish in 30min
 - with patch: 15s

_Note that this patch already improved things a lot on v2.22.1 (57s → 10s)._

```diff
diff --git a/src/rules/no-cycle.js b/src/rules/no-cycle.js
index e61c3be..d338a79 100644
--- a/src/rules/no-cycle.js
+++ b/src/rules/no-cycle.js
@@ -11,2 +11,5 @@ import docsUrl from '../docsUrl';
 
+const traversed = new Set();
 // todo: cache cycles / deep relationships for faster repeat evaluation
@@ -77,3 +80,2 @@ module.exports = {
       const untraversed = [{ mget: () => imported, route:[] }];
-      const traversed = new Set();
       function detectCycle({ mget, route }) {
```

**Comment by ljharb** [comment] 2022-01-28 23:04
@Rogdham hm, interesting. That makes sense, and seems like a good change, but it might break editor/eslintd integrations that sometimes do long-running eslint runs.

**Comment by Rogdham** [comment] 2022-01-30 10:45
Yes I agree. If for example in later runs, the `traversed` is not reset so no cycle will be detected on modified files.

But at the same times, the time improvements shows that adding caching to avoid scanning the same files again and again is a good optimisation. Maybe this means that performing cycle checks at the rule level is not the good place to do it in eslint (where rules seems to be made to work on a file independently of others), but I am not familiar with eslint enough to offer a better solution.

In any case, this discussion may be better suited for an other ticket, I only wanted to mention something that seemed to solve the current issue (although creating other problems)  to help people that know better with making a proper fix.

**Comment by ljharb** [comment] 2022-01-30 16:31
Post-install patches or forks aren’t a solution, so if the change works, it’s worth trying to upstream it. Would you be willing to make a PR?

**Comment by Rogdham** [comment] 2022-02-01 18:25
After some thinking, I don't feel confident enough to make a PR, I don't know the codebase at all and this is no simple issue.

Here are some thoughts for the next person that works on it:
 - To avoid visiting the same files again and again, some caching must be put in place;
 - My patch above may have a false negative in the following case: (assume A>B, B>C, C>B imports)
     1. Visit A (so visit B and C), no error since no cycle going back to A
     2. Visit B (fast skip since already visited) :arrow_backward: false negative
     3. Visit C (fast skip since already visited) :arrow_backward: false negative
 - Maybe look what is done on rule `import/no-unused-modules` in the case `unusedExports`, some code may be reused/factored from it
---
And again, maybe an eslint rule is not the best place to do the no-cycle check as I explained in my last comment. But I'm not familiar with eslint internals enough to tell.

Best of luck!

**Comment by soryy708** [comment] 2023-12-11 21:29
Here's an idea for how to make `import/no-cycle` faster:
https://github.com/import-js/eslint-plugin-import/issues/2937

**Comment by soryy708** [comment] 2024-09-03 18:43
An optimization to `no-cycle` was released in v 2.30.0, so try that

**Comment by ljharb** [comment] 2024-09-03 18:53
Closing; please file a new issue if you're still seeing perf issues in v2.30+.

**Closed by ljharb** 2024-09-03 18:53 UTC
Labels: bug, help wanted

**Comment by alumni** [comment] 2024-09-04 11:14
I can confirm it no longer hangs. 🎉 

Note: Adding the rule increases the runtime of eslint from 7s to 47s. This might not be related to the "no-cycle" rule in particular though, as I've noticed in the past a similar increase when enabling just the "namespace" rule or just "no-duplicates".

**Comment by ljharb** [comment] 2024-09-04 15:36
that’s still not bad - I’ve seen a large codebase take 20 minutes to lint, but reduced it to 2 with jest-eslint-runner - but if your TIMING output implicates a rule (and disabling that rule doesn’t just shift the slowness to another rule), please file an issue.
