### ISSUE TITLE
[import/no-duplicates]: issue while using --fix

### ISSUE THREAD

**Issue by slice-anuj** [import-js/eslint-plugin-import#2460] opened 2022-05-25 08:02 UTC
### Environment

Node version: v16.13.2
npm version: 8.1.2
Local ESLint version:  8.15.0
Global ESLint version: 8.15.0
Operating System: macOS

### What parser are you using?

@typescript-eslint/parser

### What did you do?

<details>
<summary>
if two import is similar then, its merge them both which create a new issue which not identified by eslint.
 

`
import {a} from "./foo"; 
import {a} from "./foo";
`

if do eslint --fix 

`
import { a,a } from "./foo"; # this create new issue duplicate identifier.
`
</summary>

### What did you expect to happen?

`
import {a} from "./foo";
`

### What actually happened?

`
import {a,a} from "./foo"; 
`

**Comment by ljharb** [comment] 2022-05-25 15:04
What version of this plugin are you using?

**Comment by slice-anuj** [comment] 2022-05-25 17:29
using  "eslint-plugin-import": "^2.26.0".

**Comment by ljharb** [comment] 2022-05-25 17:32
Looks like this is a duplicate of #2437.

**Closed by ljharb** 2022-05-25 17:32 UTC
