### ISSUE TITLE
[no-extraneous-dependencies] false positive with electron

### ISSUE THREAD

**Issue by mhatvan** [import-js/eslint-plugin-import#2175] opened 2021-08-05 06:09 UTC
The linting rule complains that `electron` should be listed as `dependency`, not `devDependency`.

Electron clearly states on https://github.com/electron/electron#installation that it should be installed as a dev dependency.

**Comment by ljharb** [comment] 2021-08-05 06:11
By default, the rule always requires things to be a dependency.

You can configure the rule to indicate in which file dev dependencies are permitted; see the docs.

**Comment by mhatvan** [comment] 2021-08-05 08:10
That doesn't seem feasible to me, because every file can potentially have a `devDependency` in it.

**Comment by ljharb** [comment] 2021-08-14 22:39
In that case, I think the only possible way to address it while keeping the rule enabled would be if we added an option that listed specific package names, and in which categories they're permitted.

… which makes this a duplicate of #903.

**Closed by ljharb** 2021-08-14 22:39 UTC
Labels: question
