### ISSUE TITLE
[import/extensions] - importing TS code with .js extension

### ISSUE THREAD

**Issue by tpluscode** [import-js/eslint-plugin-import#2170] opened 2021-07-30 06:08 UTC
I would like to configure my project so that all imports a required to be `.js`. This way I can use ES modules natively with ts-node

Right now I set a rule `"import/extensions": ["error", "always", {"ignorePackages": true}]`. It complains because obviously those `.js` files do not exist.

<img width="746" alt="Screenshot 2021-07-30 at 08 05 30" src="https://user-images.githubusercontent.com/588128/127608329-de291c4d-5ec4-4f85-87df-6b769544a394.png">

Is it possible to configure that way?

**Comment by ljharb** [comment] 2021-07-30 06:17
This entire plugin is built assuming you're using babel, not native ES Modules.

We use `resolve` for node resolution, and this does not support "exports" nor native ESM yet.

Either way, the interop story for TS and native ESM in node simply doesn't exist yet - there's basically no way to achieve this ergonomically yet.

**Comment by beamery-tomht** [comment] 2021-09-29 15:20
@tpluscode did you ever find a solution for this? 

We're experiencing the same issue! We have a TS project and use the `.js` extension for ESM, but it's super easy to miss this extension and so we're looking for an ESlint solution - but just can't find one to enforce the `.js` extension when the files are `.ts` and `.tsx`

**Comment by tpluscode** [comment] 2021-09-29 17:47
Negative but did not pursue this further

**Comment by beamery-tomht** [comment] 2021-09-29 18:28
This comment describes a workaround https://github.com/import-js/eslint-plugin-import/issues/2111#issuecomment-916395538 but you need to abandon the `no-unresolved` rule to get it working right now. Seems there's demand for this feature so would be great if this plugin could support it

**Comment by ljharb** [comment] 2021-09-29 20:52
TS recently merged a PR which might address this use case in TS itself, I believe.

**Comment by schickling** [comment] 2021-09-30 07:43
Just wanted to drop by to express here how significant this eslint rule support would be for me and the projects I'm working on. Or put the other way around: The lack of this feature currently holds me back on going all in on ESM-style `.js` file imports (which is already done by many packages e.g. by @sindresorhus.)

**Comment by ljharb** [comment] 2021-09-30 22:38
That approach is quite hostile, since it prevents anyone from using your packages unless they've also switched to native ESM, so in that case it's a good thing.

As it refers to TS, see https://github.com/import-js/eslint-plugin-import/issues/2111#issuecomment-931751520

I think this issue might be a duplicate of #2111?

**Comment by schickling** [comment] 2021-10-01 11:25
> That approach is quite hostile, since it prevents anyone from using your packages unless they've also switched to native ESM, so in that case it's a good thing.

To clarify I'm talking about internal/non-public packages. For public packages I'm still trying to provide CJS builds for a while.

**Comment by TheMrZZ** [comment] 2022-04-11 12:28
Since TypeScript 4.7 adds official support to ESM, and requires `.js` extension, this would be a very valuable feature 🙏

**Comment by SgtPooki** [comment] 2022-05-05 16:50
Very interested in this and may be putting a solution together soon if time permits. would maintainers be open to a PR for addressing this? any particular requirements you would need an acceptable PR to adhere to?

**Comment by ljharb** [comment] 2022-05-05 18:30
@SgtPooki for one, i would want the TS eslint parser to hold any TS-specific logic; but https://github.com/import-js/eslint-plugin-import/issues/2170#issuecomment-931751927 is worth a read.

**Comment by jakobo** [comment] 2022-06-08 05:17
I was able to get to a decent solution with [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/file-extension-in-import.md) in combination with this plugin. The `import/extensiosn` rule mandates an extension and bans `ts` and `tsx` as valid extensions. The `node/file-extensions-in-import` requires all relative imports include a file extension.

The downside to this is that it cannot be auto-fixed.

```json
{
  "rules": {
    "import/extensions": ["error", "always", { "ts": "never", "tsx": "never" }],
    "node/file-extension-in-import": ["error", "always"]
  }
}
```

Maybe we just look at bringing over this stylistic rule without adding more to `import/extensions`?

**Comment by JounQin** [comment] 2022-07-19 20:33
close in favor of https://github.com/import-js/eslint-import-resolver-typescript

**Closed by JounQin** 2022-07-19 20:33 UTC

**Comment by gao-sun** [comment] 2022-11-05 04:15
@JounQin would you like to elaborate how to resolve this via `eslint-import-resolver-typescript`?
